# Generated by Django 3.2.15 on 2022-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220913_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
