# Generated by Django 2.2.16 on 2022-09-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220917_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_token',
            new_name='confirmation_code',
        ),
    ]
